[package]
name = "data_store"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "data_store"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { workspace = true, features = ["init-if-needed"] }
gmx-solana-utils = { path = "../../crates/gmx-solana-utils" }
role_store = { path = "../role_store", features = ["cpi"] }
