[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
data_store = "8hJ2dGQ2Ccr5G6iEqQQEoBApRSXt7Jn8Qyf9Qf3eLBX2"
oracle = "8LmVjFpoR6hupp6WZZb6EbmupaXvivaCEk2iAHskr1en"
role_store = "H7L3aYUzR3joc6Heyonjt1thpWdtwYcTVQvCrB2xDsdi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json --require utils/fixtures.ts -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.mainnet-beta.solana.com"
bind_address = "127.0.0.1"

[[test.genesis]]
address = "HEvSKofvBgfaexv23kMabbYqxasxU3mQ4ibBMEmJWHny"
program = "external-programs/chainlink-store.so"

[[test.validator.clone]]
address = "Cv4T27XbjVoKUYwP72NQQanvZeA7W4YF9L4EnYT9kx5o"
