[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
gmsol_store = "gmX4GEZycT14vqJ3yDoCA5jW53vBaSQpQDYNDXtkWt1"
gmsol-treasury = "trekjLtMLpfJHVxBVhng99koG3LPAxzTBLMYco9vfJQ"
gmsol-timelock = "timedreYasWZUyAgofdmjFVJwk3LKZZq6QJtgpc1aqv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --test anchor --features anchor-test -- $GMSOL_TEST"

[test]
startup_wait = 15000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "HEvSKofvBgfaexv23kMabbYqxasxU3mQ4ibBMEmJWHny"
program = "external-programs/chainlink-store.so"

[[test.genesis]]
address = "rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ"
program = "external-programs/pyth-receiver.so"

[[test.genesis]]
address = "pythWSnswVUd12oZpeFP8e9CVaEqJg25g1Vtc2biRsT"
program = "external-programs/pyth-push-oracle.so"

[[test.genesis]]
address = "HDwcJBJXjL9FpJ7UBsYBtaDjsBUhuLCUYoz3zr8SWWaQ"
program = "external-programs/wormhole.so"

[test.validator]
bind_address = "127.0.0.1"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

# BTC Data Feed (Chainlink)
[[test.validator.clone]]
address = "Cv4T27XbjVoKUYwP72NQQanvZeA7W4YF9L4EnYT9kx5o"

# SOL Data Feed (Chainlink)
[[test.validator.clone]]
address = "CH31Xns5z3M1cTAbKW34jcxPPciazARpijcHj9rxtemt"

# USDC Data Feed (Chainlink)
[[test.validator.clone]]
address = "GzGuoKXE8Unn7Vcg1DtomwD27tL4bVUpSK2M1yk6Xfz5"

# WBTC Token Mint
[[test.validator.clone]]
address = "3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh"

# Pyth receiver program
[[test.validator.clone]]
address = "rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ"

# BTC Data Feed (Pyth)
[[test.validator.clone]]
address = "4cSM2e6rvbGQUFiJbqytoVMi5GgghSMr8LwVrT9VPSPo"

# SOL Data Feed (Pyth)
[[test.validator.clone]]
address = "7UVimffxr9ow1uXYxsr4LHAcV58mLzhmwaeKvJ1pjLiE"

# USDC Data Feed (Pyth)
[[test.validator.clone]]
address = "Dpw1EAVrSB1ibxiDQyTAW6Zip3J4Btk2x4SgApQCeFbX"

# Wormhole Guardian Set account
[[test.validator.clone]]
address = "5gxPdahvSzcKySxXxPuRXZZ9s6h8hZ88XDVKavWpaQGn"

# Pyth Config account
[[test.validator.clone]]
address = "DaWUKXCyXsnzcvLUyeJRWou8KTn7XtadgTsdhJ6RHS7b"
