[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
gmx_solana = "2mzvgXHKwkGTQpBWxDD7ebbHK4V1UpobmoCCFd9eQ4sa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/orion/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
