[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
role = "EUE8AaF2X5Z7Pbi3j3DU3zquhe9QpuANqZWLvDQM1vJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/orion/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
