[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
data_store = "8hJ2dGQ2Ccr5G6iEqQQEoBApRSXt7Jn8Qyf9Qf3eLBX2"
market = "AFxZM92h6tryw4hZx2puJRWjA4CQSkxmVkzJrDWJgJAL"
oracle = "8LmVjFpoR6hupp6WZZb6EbmupaXvivaCEk2iAHskr1en"
role_store = "H7L3aYUzR3joc6Heyonjt1thpWdtwYcTVQvCrB2xDsdi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json --require utils/fixtures.ts -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "HEvSKofvBgfaexv23kMabbYqxasxU3mQ4ibBMEmJWHny"
program = "external-programs/chainlink-store.so"

[test.validator]
bind_address = "127.0.0.1"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

# BTC Data Feed
[[test.validator.clone]]
address = "Cv4T27XbjVoKUYwP72NQQanvZeA7W4YF9L4EnYT9kx5o"

# SOL Data Feed
[[test.validator.clone]]
address = "CH31Xns5z3M1cTAbKW34jcxPPciazARpijcHj9rxtemt"

# WBTC Token Mint
[[test.validator.clone]]
address = "3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh"

# We don't need to clone the WSOL Mint account.
# # WSOL Token Mint
# [[test.validator.clone]]
# address = "So11111111111111111111111111111111111111112"
