[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
data_store = "HLkiY9JScepfVa8UJ9dfy3gnKfQhWvFZ4iK8hANxuTCy"
oracle = "wtj96FFfr7r8hvuyDTt8mZ85RcYjGEFqmQGZozSA8S9"
role_store = "KLAh3o2hMDJT26zBxv6RYrxcUxBjPCEeSt3Q1rS4JMU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
