[workspace]
resolver = "2"
members = ["programs/*", "crates/*"]

[workspace.dependencies]
anchor-lang = "0.30.0"
anchor-spl = { version = "0.30.0", default_features = false }
thiserror = "1.0.58"
bytemuck = "1.15.0"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
