[package]
name = "gmsol-store"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
name = "gmsol_store"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
debug = []
display = []
utils = []
devnet = []
serde = ["dep:serde"]
enum-iter = []

[dependencies]
bytemuck = { workspace = true }
anchor-lang = { workspace = true, features = ["init-if-needed", "event-cpi"] }
gmsol-model = { workspace = true, features = ["u128", "solana"] }
gmx-solana-utils = { path = "../../crates/gmx-solana-utils" }
dual-vec-map = { path = "../../crates/dual-vec-map" }
anchor-spl = { workspace = true, default-features = false, features = [
    "token",
    "token_2022",
    "token_2022_extensions",
] }
bitmaps = { workspace = true }
chainlink_solana = { workspace = true }
num_enum = { workspace = true }
static_assertions = { workspace = true }
clap = { workspace = true, optional = true }
pyth-sdk-solana = { workspace = true }
pyth-solana-receiver-sdk = { workspace = true }
paste = { workspace = true }
strum = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"], optional = true }
indexmap = { workspace = true }
