[package]
name = "gmsol-utils"
version.workspace = true
edition.workspace = true

[dependencies]
anchor-lang = { workspace = true }
thiserror = { workspace = true }
paste = { workspace = true }
bytemuck = { workspace = true }
static_assertions = { workspace = true }
