[package]
name = "gmsol-utils"
version.workspace = true
edition.workspace = true

[features]
debug = []

[dependencies]
anchor-lang = { workspace = true }
thiserror = { workspace = true }
paste = { workspace = true }
bytemuck = { workspace = true }
static_assertions = { workspace = true }
ruint = { workspace = true, default-features = false }
