[package]
name = "gmsol-sdk"
documentation = "https://docs.rs/gmsol-sdk"
version.workspace = true
edition.workspace = true
license-file.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true

[lib]
crate-type = ["cdylib"]

[features]
default = []
treasury = ["gmsol-programs/treasury"]
wasm = ["wasm-bindgen"]

[dependencies]
gmsol-programs = { workspace = true }
gmsol-model = { workspace = true, features = ["u128"] }

# Dependencies for the `wasm` feature
wasm-bindgen = { workspace = true, optional = true }
