[package]
name = "gmsol-sdk"
documentation = "https://docs.rs/gmsol-sdk"
version.workspace = true
edition.workspace = true
license-file.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true

[lib]
crate-type = ["cdylib"]

[features]
default = ["treasury", "market-graph"]
treasury = ["gmsol-programs/treasury"]
js = [
    "wasm-bindgen",
    "serde",
    "serde-wasm-bindgen",
    "gmsol-programs/wasm-bindgen",
    "tsify-next",
    "gmsol-model/js",
]
serde = ["dep:serde", "gmsol-model/serde"]
market-graph = ["petgraph", "rust_decimal/maths"]

[dependencies]
gmsol-programs = { workspace = true, features = ["model"] }
gmsol-model = { workspace = true, features = ["u128"] }
thiserror = { workspace = true }
base64 = { workspace = true }
solana-sdk = { workspace = true }
either = { workspace = true }
rust_decimal = { workspace = true, default_features = false, features = [
    "std",
] }

tracing = { workspace = true, optional = true }

# Dependencies for the `wasm` feature
wasm-bindgen = { workspace = true, optional = true }
serde-wasm-bindgen = { workspace = true, optional = true }
tsify-next = { workspace = true, optional = true, features = ["js"] }

# Dependencies for the `serde` feature
serde = { workspace = true, optional = true, features = ["derive"] }

# Dependencies for the `market-graph` feature
petgraph = { workspace = true, optional = true, default-features = false, features = [
    "std",
    "stable_graph",
] }

[build-dependencies]
cfg_aliases = { workspace = true }

[dev-dependencies]
rust_decimal_macros = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
