[package]
name = "gmsol-sdk"
documentation = "https://docs.rs/gmsol-sdk"
version.workspace = true
edition.workspace = true
license-file.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true

[lib]
crate-type = ["cdylib"]

[features]
default = []
treasury = ["gmsol-programs/treasury"]
js = [
    "wasm-bindgen",
    "serde",
    "serde-wasm-bindgen",
    "gmsol-programs/wasm-bindgen",
    "tsify-next",
    "gmsol-model/js",
]
serde = ["dep:serde", "gmsol-model/serde"]

[dependencies]
gmsol-programs = { workspace = true, features = ["model"] }
gmsol-model = { workspace = true, features = ["u128"] }
thiserror = { workspace = true }
base64 = { workspace = true }

# Dependencies for the `wasm` feature
wasm-bindgen = { workspace = true, optional = true }
serde-wasm-bindgen = { workspace = true, optional = true }
tsify-next = { workspace = true, optional = true, features = ["js"] }

# Dependencies for the `serde` feature
serde = { workspace = true, optional = true, features = ["derive"] }
