[package]
name = "gmsol"
version.workspace = true
edition.workspace = true

[[bin]]
name = "gmsol"
path = "src/cli/main.rs"
required-features = ["cli"]

[features]
cli = [
    "pyth-pull-oracle",
    "tokio/full",
    "clap",
    "tracing-subscriber",
    "shellexpand",
    "anchor-syn",
    "heck",
    "toml",
    "serde_with",
    "hex",
    "indexmap",
]
ui = ["cli", "poem/embed", "rust-embed"]
clap = ["dep:clap", "gmsol-store/clap"]
devnet = ["gmsol-store/devnet", "gmsol-exchange/devnet"]
pyth-pull-oracle = [
    "reqwest/stream",
    "url",
    "serde",
    "serde_json",
    "eventsource-stream",
    "pythnet-sdk",
    "pyth-solana-receiver-sdk",
    "byteorder",
]
rust-embed = ["dep:rust-embed"]
poem = ["dep:poem"]

[dependencies]
# Dependencies for cli
clap = { workspace = true, optional = true, features = ["derive", "env"] }
tracing-subscriber = { workspace = true, optional = true, features = [
    "env-filter",
] }
shellexpand = { workspace = true, optional = true }
toml = { workspace = true, optional = true }
serde_with = { workspace = true, optional = true, features = ["indexmap_2"] }
hex = { workspace = true, optional = true }
indexmap = { workspace = true, optional = true, features = ["serde"] }

# Dependencies for pyth support
reqwest = { workspace = true, optional = true, features = ["json"] }
url = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
serde = { workspace = true, optional = true, features = ["derive"] }
eventsource-stream = { workspace = true, optional = true }
pythnet-sdk = { workspace = true, optional = true }
pyth-solana-receiver-sdk = { workspace = true, optional = true }
anchor-syn = { workspace = true, optional = true }
heck = { workspace = true, optional = true }
byteorder = { workspace = true, optional = true }

# Other deps
gmx-solana-utils = { path = "../gmx-solana-utils" }
gmsol-store = { workspace = true, features = [
    "no-entrypoint",
    "debug",
    "display",
    "utils",
    "serde",
    "enum-iter",
] }
gmsol-exchange = { workspace = true, features = ["no-entrypoint", "debug"] }
gmx-core = { path = "../gmx-core" }

pyth-sdk = { workspace = true }
typed-builder = { workspace = true }
eyre = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
base64 = { workspace = true }
anchor-client = { workspace = true, features = ["async"] }
anchor-spl = { workspace = true, default-features = false, features = [
    "token",
    "token_2022",
    "associated_token",
] }
bytemuck = { workspace = true }
rand = { workspace = true }
futures-util = { workspace = true }
spl-governance = { workspace = true, features = ["no-entrypoint"] }
strum = { workspace = true }
rust-embed = { workspace = true, optional = true }
poem = { workspace = true, optional = true }
