[package]
name = "gmsol"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gmsol"
path = "src/cli/main.rs"
required-features = ["cli"]

[features]
cli = [
    "pyth",
    "tokio/full",
    "clap",
    "tracing-subscriber",
    "shellexpand",
    "anchor-syn",
    "heck",
]
clap = ["dep:clap", "data_store/clap"]
devnet = ["data_store/devnet", "exchange/devnet"]
pyth = [
    "reqwest/stream",
    "futures-util",
    "url",
    "serde",
    "serde_json",
    "eventsource-stream",
    "pythnet-sdk",
    "pyth-solana-receiver-sdk",
]

[dependencies]
eyre = { version = "0.6.12" }
tokio = "1.37.0"
thiserror = "1.0.58"
tracing = "0.1.40"
base64 = "0.22.0"
anchor-client = { version = "0.30.0", features = ["async"] }
anchor-spl = { workspace = true, default_features = false, features = [
    "token",
    "token_2022",
    "associated_token",
] }
bytemuck = { workspace = true }
gmx-solana-utils = { path = "../gmx-solana-utils" }
data_store = { path = "../../programs/data_store", features = [
    "no-entrypoint",
    "debug",
    "utils",
] }
exchange = { path = "../../programs/exchange", features = [
    "no-entrypoint",
    "debug",
] }
rand = { version = "0.8.5" }

# Dependencies for cli
clap = { workspace = true, optional = true, features = ["derive", "env"] }
tracing-subscriber = { version = "0.3.18", optional = true, features = [
    "env-filter",
] }
shellexpand = { version = "3.1.0", optional = true }
pyth-sdk = "0.8.0"

# Dependencies for pyth support
reqwest = { version = "0.12.4", optional = true }
futures-util = { version = "0.3.30", optional = true }
url = { version = "2.5.0", optional = true }
serde_json = { version = "1.0.117", optional = true }
serde = { version = "1.0.201", optional = true, features = ["derive"] }
eventsource-stream = { version = "0.2.3", optional = true }
pythnet-sdk = { version = "2.1.0", optional = true }
pyth-solana-receiver-sdk = { workspace = true, optional = true }
anchor-syn = { version = "0.30.0", optional = true }
heck = { version = "0.5.0", optional = true }
