[package]
name = "gmsol"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gmsol"
path = "src/cli/main.rs"
required-features = ["cli"]

[features]
cli = ["tokio/full", "eyre", "clap", "tracing-subscriber", "shellexpand"]

[dependencies]
tokio = "1.37.0"
thiserror = "1.0.58"
tracing = "0.1.40"
anchor-client = { version = "0.29.0", features = ["async"] }
data_store = { path = "../../programs/data_store", features = [
    "no-entrypoint",
    "debug",
] }

# Dependencies for cli
eyre = { version = "0.6.12", optional = true }
clap = { version = "4.5.0", optional = true, features = ["derive", "env"] }
tracing-subscriber = { version = "0.3.18", optional = true, features = [
    "env-filter",
] }
shellexpand = { version = "3.1.0", optional = true }
