[alias]
gmsol = [
    "run",
    "--bin",
    "gmsol",
    "--features",
    "cli,squads,migration",
    "--locked",
    "--",
]
gmsol-devnet = [
    "run",
    "--bin",
    "gmsol",
    "--features",
    "cli,devnet,squads,migration",
    "--locked",
    "--",
]
install-gmsol = [
    "install",
    "--path",
    "crates/gmsol",
    "--features",
    "cli,squads,migration",
    "--locked",
]
install-gmsol-devnet = [
    "install",
    "--path",
    "crates/gmsol",
    "--features",
    "cli,devnet,squads,migration",
    "--locked",
]
