[ADVTTETv4Nbg7a2jPZWCxJ7uoQsPoewi4sJhK9DqpSpe]
enable = false
# # Market Config Buffer Account to be used if provided.
# buffer = ""
swap_impact_exponent = "100_000_000_000_000_000_000"                              # `1`, for single pool
swap_impact_positive_factor = "0"
swap_impact_negative_factor = "0"
swap_fee_receiver_factor = "70_000_000_000_000_000_000"                           # `70%`
swap_fee_factor_for_positive_impact = "0"                                         # for single pool
swap_fee_factor_for_negative_impact = "0"
min_position_size_usd = "100_000_000_000_000_000_000"                             # `1`
min_collateral_value = "100_000_000_000_000_000_000"                              # `1`
min_collateral_factor = "1_000_000_000_000_000_000"                               # `0.01`, x100 max leverage for most indexs
min_collateral_factor_for_open_interest_multiplier_for_long = "380_000_000_000"   # `0.0000000038`, minCollateralFactor of 0.01 (1%) when open interest is 2,600,000 USD
min_collateral_factor_for_open_interest_multiplier_for_short = "380_000_000_000"
max_positive_position_impact_factor = "500_000_000_000_000_000"                   # `0.5%`
max_negative_position_impact_factor = "500_000_000_000_000_000"
max_position_impact_factor_for_liquidations = "0"
position_impact_exponent = "200_000_000_000_000_000_000"                          # `2`
position_impact_positive_factor = "10_000_000_000_000"                            # `0.0000001`, for most indexs with low liquidity
position_impact_negative_factor = "20_000_000_000_000"
order_fee_receiver_factor = "70_000_000_000_000_000_000"                          # `70%`
order_fee_factor_for_positive_impact = "50_000_000_000_000_000"                   # `0.05%`
order_fee_factor_for_negative_impact = "70_000_000_000_000_000"                   # `0.07%`
liquidation_fee_receiver_factor = "70_000_000_000_000_000_000"                    # `70%`
liquidation_fee_factor = "200_000_000_000_000_000"                                # `0.2%`
position_impact_distribute_factor = "230_000_000_000_000_000"                     # `0.0023` for most indexs on [USDC-USDC]
min_position_impact_pool_amount = "1_500_000_000"                                 # `1500` for most indexs on [USDC-USDC]
borrowing_fee_receiver_factor = "70_000_000_000_000_000_000"                      # `70%`
borrowing_fee_factor_for_long = "2_780_000_000_000"                               # `0.0000000278`, about 0.0045% max rate per hour
borrowing_fee_factor_for_short = "2_780_000_000_000"
borrowing_fee_exponent_for_long = "100_000_000_000_000_000_000"                   # `1`
borrowing_fee_exponent_for_short = "100_000_000_000_000_000_000"
borrowing_fee_optimal_usage_factor_for_long = "75_000_000_000_000_000_000"        # `75%`
borrowing_fee_optimal_usage_factor_for_short = "75_000_000_000_000_000_000"       # `75%`
borrowing_fee_base_factor_for_long = "1_902_587_519_025"                          # `60%` per year
borrowing_fee_base_factor_for_short = "1_902_587_519_025"                         # `60%` per year
borrowing_fee_above_optimal_usage_factor_for_long = "4_756_468_797_564"           # `150%` per year
borrowing_fee_above_optimal_usage_factor_for_short = "4_756_468_797_564"          # `150%` per year
funding_fee_exponent = "100_000_000_000_000_000_000"                              # `1`
funding_fee_factor = "2_000_000_000_000"                                          # `0.00000002`
funding_fee_max_factor_per_second = "1_500_000_000_000"                           # `0.000000015`
funding_fee_min_factor_per_second = "30_000_000_000"                              # `0.0000000003`
funding_fee_increase_factor_per_second = "116_000_000"                            # `0.00000000000116`
funding_fee_decrease_factor_per_second = "0"
funding_fee_threshold_for_stable_funding = "5_000_000_000_000_000_000"            # `0.05`
funding_fee_threshold_for_decrease_funding = "0"
reserve_factor = "50_000_000_000_000_000_000"                                     # `0.5` for single pool
open_interest_reserve_factor = "45_000_000_000_000_000_000"                       # `0.45` for single pool
max_pnl_factor_for_long_deposit = "60_000_000_000_000_000_000"                    # `60%`, synthethicMarket
max_pnl_factor_for_short_deposit = "60_000_000_000_000_000_000"
max_pnl_factor_for_long_withdrawal = "60_000_000_000_000_000_000"
max_pnl_factor_for_short_withdrawal = "60_000_000_000_000_000_000"
max_pnl_factor_for_long_trader = "60_000_000_000_000_000_000"
max_pnl_factor_for_short_trader = "60_000_000_000_000_000_000"
max_pnl_factor_for_long_adl = "55_000_000_000_000_000_000"
max_pnl_factor_for_short_adl = "55_000_000_000_000_000_000"
min_pnl_factor_after_long_adl = "50_000_000_000_000_000_000"
min_pnl_factor_after_short_adl = "50_000_000_000_000_000_000"
max_pool_amount_for_long_token = "900_000_000_000"                                # `900,000` for most indexs on [USDC-USDC]
max_pool_amount_for_short_token = "900_000_000_000"
max_pool_value_for_deposit_for_long_token = "75_000_000_000_000_000_000_000_000"  # `750,000` for most indexs on [USDC-USDC]
max_pool_value_for_deposit_for_short_token = "75_000_000_000_000_000_000_000_000"
max_open_interest_for_long = "45_000_000_000_000_000_000_000_000"                 # `450,000` for most indexs on [USDC-USDC]
max_open_interest_for_short = "45_000_000_000_000_000_000_000_000"
min_tokens_for_first_deposit = "0"
