[6UU9sF5fryafHDYPcmVcV7ucfnYs6iMVcvb8p7SBQgTc]
enable = false
# # Market Config Buffer Account to be used if provided.
# buffer = ""
swap_impact_exponent = "1"                                                        # for single pool
swap_impact_positive_factor = "0"
swap_impact_negative_factor = "0"
swap_fee_receiver_factor = "0.7"                                                  # `70%`
swap_fee_factor_for_positive_impact = "0"                                         # for single pool
swap_fee_factor_for_negative_impact = "0"
min_position_size_usd = "1"
min_collateral_value = "1"
min_collateral_factor = "0.01"                                                    # `0.01`, x100 max leverage for most indexs
min_collateral_factor_for_open_interest_multiplier_for_long = "0.0000000038"      # minCollateralFactor of 0.01 (1%) when open interest is 2,600,000 USD
min_collateral_factor_for_open_interest_multiplier_for_short = "0.0000000038"
max_positive_position_impact_factor = "0.005"
max_negative_position_impact_factor = "0.005"
max_position_impact_factor_for_liquidations = "0"
position_impact_exponent = "2"
position_impact_positive_factor = "0.0000001"                                     # `0.0000001`, for most indexs with low liquidity
position_impact_negative_factor = "0.0000002"
order_fee_receiver_factor = "0.7"                                                 # `70%`
order_fee_factor_for_positive_impact = "0.0005"                                   # `0.05%`
order_fee_factor_for_negative_impact = "0.0007"                                   # `0.07%`
liquidation_fee_receiver_factor = "0.7"                                           # `70%`
liquidation_fee_factor = "0.002"                                                  # `0.2%`
position_impact_distribute_factor = "1"                                           # distributing `1` unit tokens per second
min_position_impact_pool_amount = "1500"                                          # reserving at least `1500` tokens (not unit tokens) in the PI pool
borrowing_fee_receiver_factor = "0.7"                                             # `70%`
borrowing_fee_factor_for_long = "0.0000000278"                                    # `0.0000000278`, about 0.0045% max rate per hour
borrowing_fee_factor_for_short = "0.0000000278"
borrowing_fee_exponent_for_long = "1"
borrowing_fee_exponent_for_short = "1"
borrowing_fee_optimal_usage_factor_for_long = "0.75"                              # `75%`
borrowing_fee_optimal_usage_factor_for_short = "0.75"                             # `75%`
borrowing_fee_base_factor_for_long = "0.00000001902587519025"                     # `60%` per year
borrowing_fee_base_factor_for_short = "0.00000001902587519025"                    # `60%` per year
borrowing_fee_above_optimal_usage_factor_for_long = "0.00000004756468797564"      # `150%` per year
borrowing_fee_above_optimal_usage_factor_for_short = "0.00000004756468797564"     # `150%` per year
funding_fee_exponent = "1"
funding_fee_factor = "0.00000002"
funding_fee_max_factor_per_second = "0.000000015"
funding_fee_min_factor_per_second = "0.0000000003"
funding_fee_increase_factor_per_second = "0.00000000000116"
funding_fee_decrease_factor_per_second = "0"
funding_fee_threshold_for_stable_funding = "0.05"
funding_fee_threshold_for_decrease_funding = "0"
reserve_factor = "0.5"                                                            # `0.5` for single pool
open_interest_reserve_factor = "0.45"                                             # `0.45` for single pool
max_pnl_factor_for_long_deposit = "0.6"                                           # `60%`, synthethicMarket
max_pnl_factor_for_short_deposit = "0.6"
max_pnl_factor_for_long_withdrawal = "0.6"
max_pnl_factor_for_short_withdrawal = "0.6"
max_pnl_factor_for_long_trader = "0.6"
max_pnl_factor_for_short_trader = "0.6"
max_pnl_factor_for_long_adl = "0.55"
max_pnl_factor_for_short_adl = "0.55"
min_pnl_factor_after_long_adl = "0.5"
min_pnl_factor_after_short_adl = "0.5"
max_pool_amount_for_long_token = "900000"                                         # `900,000` for most indexs on [USDC-USDC]
max_pool_amount_for_short_token = "900000"
max_pool_value_for_deposit_for_long_token = "750000"                              # `750,000` for most indexs on [USDC-USDC]
max_pool_value_for_deposit_for_short_token = "750000"
max_open_interest_for_long = "450000"                                             # `450,000` for most indexs on [USDC-USDC]
max_open_interest_for_short = "450000"
min_tokens_for_first_deposit = "0"
