min_tokens_for_first_deposit = "1"
shift_min_interval = "2h"
shift_max_price_impact_factor = "0.001"
shift_min_value = "1"

[338dwWNqFoXsaw8UzGjVnxqzvrfLWqtMTSUSeZXwaQnY]
max_amount = "5000000"
max_value = "5000000"
is_deposit_allowed = false

[7VuNcy1A22rYfiaqaqbGZr9z9PmmahAsc6RNET165GiW]
max_amount = "5000000"
max_value = "5000000"
is_deposit_allowed = false
