[SOL]
address = "11111111111111111111111111111111"
synthetic = 9
enable = true
update = false
expected_provider = "pyth"
precision = 4
heartbeat_duration = 120

[SOL.feeds]
pyth_feed_id = "0xef0d8b6fda2ceba41da15d4095d1da392a0d2f8ed0c6c7bc0f4cfac8c280b56d"

[WSOL]
address = "So11111111111111111111111111111111111111112"
enable = true
update = false
expected_provider = "pyth"
precision = 4
heartbeat_duration = 120

[WSOL.feeds]
pyth_feed_id = "0xef0d8b6fda2ceba41da15d4095d1da392a0d2f8ed0c6c7bc0f4cfac8c280b56d"

[USDG]
address = "usd3Kfir4jHvuyhVVWXvQ4YumrvysHSCyghTehg7UKT"
enable = true
update = false
expected_provider = "pyth"
precision = 4
heartbeat_duration = 120

[USDG.feeds]
pyth_feed_id = "0xeaa020c61cc479712813461ce153894a96a6c00b21ed0cfc2798d1f9a9e9c94a"

[BTC]
address = "btcx3SkD6MNhkuKmgi3nayRbc9SQXomeuHMCxJJFaew"
enable = true
update = false
expected_provider = "pyth"
precision = 2
heartbeat_duration = 120

[BTC.feeds]
pyth_feed_id = "0xe62df6c8b4a85fe1a67db44dc12de5db330f7ac66b72dc658afedf0f4a415b43"
