[package]
name = "gmsol-decode"
version.workspace = true
edition.workspace = true
license-file.workspace = true
description.workspace = true
repository.workspace = true
documentation = "https://docs.rs/gmsol-decode"
readme.workspace = true
keywords.workspace = true

[features]
default = []
gmsol = ["gmsol-store/debug", "gmsol-store/display"]
gmsol-programs = ["dep:gmsol-programs"]
solana-decoder = ["solana-transaction-status", "bs58"]

[dependencies]
gmsol-store = { workspace = true, optional = true }
gmsol-programs = { workspace = true, optional = true }

tracing = { workspace = true }
thiserror = { workspace = true }
anchor-lang = { workspace = true }
solana-sdk = { workspace = true }
base64 = { workspace = true }
bytemuck = { workspace = true }
paste = { workspace = true }
cfg-if = { workspace = true }

solana-transaction-status = { workspace = true, optional = true }
bs58 = { workspace = true, optional = true }

[package.metadata.docs.rs]
features = ["gmsol-programs", "solana-decoder"]
rustdoc-args = ["--cfg", "docsrs"]
