[package]
name = "gmsol-treasury"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
name = "gmsol_treasury"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
debug-msg = []
idl-build = ["anchor-lang/idl-build", "gmsol-store/idl-build"]
debug = ["gmsol-store/debug"]
multi-store = ["gmsol-store/multi-store"]

[dependencies]
anchor-lang = { workspace = true }
gmsol-store = { workspace = true, features = ["cpi"] }
